name: SGFROTA
on: push

jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-latest
    with:
        server: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    steps:
        - uses: actions/checkout@v1
        - uses: ./.github/actions/composer